name = "simstim"
description = "Simple theme for dreamers"
min_version = "0.1.0"
license = "MIT"
homepage = "https://github.com/oneeronaut/simstim"
# demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[author]
name = "oneeronaut"
homepage = "https://www.oneeronaut.com"
